version: "3.11"
services:
  db:
    container_name: db
    image: postgres:15
    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:7

  app:
    container_name: app
    build:
      context: .
    env_file:
      - .env
    command: ["./scripts/start.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery:
    container_name: celery
    build:
      context: .
    command: ["./scripts/celery.sh", "celery"]
    env_file:
      - .env
    depends_on:
      - redis
