version: "3.11"
services:
  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:7

  app:
    container_name: app
    build:
      context: .
    volumes:
      - ./:/code
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery:
    container_name: celery
    build:
      context: .
    command: celery --app=app.tasks.celery:celery worker -l INFO
    env_file:
      - .env
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  postgresdata:
  grafanadata:
  prometheusdata:
